# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "eaglestream"
BBFILE_PATTERN_eaglestream = ""
BBFILE_PRIORITY_eaglestream = "5"
LAYERSERIES_COMPAT_eaglestream = "hardknott honister"
