KMACHINE = "aspeed"
KERNEL_DEVICETREE = "aspeed-bmc-phoenix-morocity.dtb"

require conf/machine/include/ast2500.inc
require conf/machine/include/obmc-bsp-common.inc
require conf/machine/include/phoenix.inc

UBOOT_MACHINE = "ast_g5_phy_config"

VIRTUAL-RUNTIME_skeleton_workbook = "${MACHINE}-config"
VIRTUAL-RUNTIME_obmc-host-state-manager = "x86-power-control"
VIRTUAL-RUNTIME_obmc-chassis-state-manager = "x86-power-control"

FLASH_SIZE = "65536"
FLASH_KERNEL_OFFSET:flash-65536 = "1024"
FLASH_ROFS_OFFSET:flash-65536 = "8192"
FLASH_RWFS_OFFSET:flash-65536 = "49152"

VOLATILE_LOG_DIR = "no"

