/*
// Copyright (c) 2021 Phoenix Technologies Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/

const char *sdr_rec_01[]= {
    "RecordID",
    "SDRVersion",
    "RecordType",
    "RecordLength",
    "SensorOwnerID",
    "SensorOwnerLUN",
    "SensorNumber",
    "EntityID",
    "EntityInstance",
    "SensorInitialization",
    "SensorCapabilities",
    "SensorType",
    "Event/ReadingType",
    "LowerThresholdReadingMask",
    "UpperThresholdReadingMask",
    "Settable/ReadableThresholdMask",
    "SensorUnits1",
    "SensorUnits2-BaseUnit",
    "SensorUnits3-ModifierUnit",
    "Linearization",
    "M",
    "M-Tolerance",
    "B",
    "B-Accuracy",
    "Accuracy-Accuracyexponent",
    "Rexponent-Bexponent",
    "AnalogCharacteristicsFlags",
    "NominalReading",
    "NormalMaximum",
    "NormalMinimum",
    "SensorMaximumReading",
    "SensorMinimumReading",
    "UpperNon-RecoverableThreshold",
    "UpperCriticalThreshold",
    "UpperNon-CriticalThreshold",
    "LowerNon-RecoverableThreshold",
    "LowerCriticalThreshold",
    "LowerNon-CriticalThreshold",
    "Positive-thresholdHysteresisvalue",
    "Negative-thresholdHysteresisvalue",
    "Reserved",
    "Reserved",
    "OEM",
    "LengthCode",
    "SensorName",
};

const char *sdr_rec_02[]= {
    "RecordID",
    "SDRVersion",
    "RecordType",
    "RecordLength",
    "SensorOwnerID",
    "SensorOwnerLUN",
    "SensorNumber",
    "EntityID",
    "EntityInstance",
    "SensorInitialization",
    "SensorCapabilities",
    "SensorType",
    "Event/ReadingType",
    "AssertionMask",
    "DeAssertionMask",
    "Settable/ReadableThresholdMask",
    "SensorUnits1",
    "SensorUnits2-BaseUnit",
    "SensorUnits3-ModifierUnit",
    "SensorRecordSharing",
    "Positive-thresholdHysteresisvalue",
    "Negative-thresholdHysteresisvalue",
    "Reserved",
    "Reserved",
    "Reserved",
    "OEM",
    "LengthCode",
    "SensorName",
};

const char *sdr_rec_03[]= {
    "RecordID",
    "SDRVersion",
    "RecordType",
    "RecordLength",
    "SensorOwnerID",
    "SensorOwnerLUN",
    "SensorNumber",
    "EntityID",
    "EntityInstance",
    "SensorType",
    "Event/ReadingType",
    "SensorRecordSharing",
    "Reserved",
    "OEM",
    "LengthCode",
    "SensorName",
};

const char *sdr_rec_11[]= {
    "RecordID",
    "SDRVersion",
    "RecordType",
    "RecordLength",
    "SlaveAddress",
    "FRUDeviceID",
    "Log/physicalID",
    "ChannelNumber",
    "Reserved",
    "DeviceType",
    "DeviceTypeModifier",
    "EntityID",
    "EntityInstance",
    "OEM",
    "LengthCode",
    "SensorName",
};

const char *sdr_rec_12[]= {
    "RecordID",
    "SDRVersion",
    "RecordType",
    "RecordLength",
    "SlaveAddress",
    "ChannelNumber",
    "powerstatenotification",
    "DeviceCapablities",
    "Reserved",
    "Reserved",
    "Reserved",
    "EntityID",
    "EntityInstance",
    "OEM",
    "LengthCode",
    "SensorName",
};

const char *sdr_rec_c0[]= {
    "RecordID",
    "SDRVersion",
    "RecordType",
    "RecordLength",
    "OEMData1",
    "OEMData2",
    "OEMData3",
    "OEMData4",
    "OEMData5",
    "OEMData6",
    "OEMData7",
    "OEMData8",
    "OEMData9",
    "OEMData10",
    "OEMData11",
    "OEMData12",
    "OEMData13",
    "OEMData14",
    "OEMData15",
    "OEMData16",
    "OEMData17",
    "OEMData18",
    "OEMData19",
    "OEMData20",
    "OEMData21",
    "OEMData22",
    "OEMData23",
    "OEMData24",
    "OEMData25",
    "OEMData26",
    "OEMData27",
    "OEMData28",
    "OEMData29",
    "OEMData30",
};
